name: Ben Burwell
markdown: redcarpet
pygments: true
keywords:
    - ben burwell
    - freelance
    - designer
    - developer
description: "Computer science student, hacker. Passionate about kerning and coffee."
# sass:
#     style: :compressed
permalink: /:categories/:title/
