# Config options
markdown: kramdown
sass:
  style: :compressed
  sass_dir: _sass
permalink: /posts/:title/
gems:
  - jekyll-redirect-from
  - jekyll-feed
timezone: America/New_York

# Site-level data
name: Ben Burwell
keywords:
  - ben burwell
  - software engineer
  - developer
  - cryptography
  - lighting design
description: "I make things."
excerpt_separator: <!--more-->
