name: Ben Burwell
markdown: redcarpet
highlighter: pygments
keywords:
    - ben burwell
    - freelance
    - designer
    - developer
description: "Computer science student, hacker. Passionate about kerning and coffee."
sass:
    style: :compressed
    sass_dir: _sass
permalink: /:categories/:title/
