# Config options
markdown: kramdown
sass:
  style: :compressed
  sass_dir: _sass
plugins:
  - jekyll-redirect-from
  - jekyll-feed
timezone: America/New_York

# Site-level data
name: Ben Burwell
excerpt_separator: <!--more-->
layout: master
permalink: /:slug.html

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:title/

