# Config options
markdown: redcarpet
highlighter: pygments
sass:
    style: :compressed
    sass_dir: _sass
permalink: /posts/:title/
gems:
    - jekyll-redirect-from
timezone: America/New_York
lsi: true

# Site-level data
name: Ben Burwell
keywords:
    - ben burwell
    - software engineer
    - developer
    - web applications
description: "I like to make awesome things with code. Software engineer, student, hacker. Passionate about kerning and coffee."
